# Generated by Django 5.0.7 on 2024-07-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_task_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign',
            old_name='supervisor',
            new_name='supervisor_approved',
        ),
        migrations.AddField(
            model_name='assign',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
