# Generated by Django 5.0.7 on 2024-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_assign_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
